// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2.DAL;

#nullable disable

namespace Parcial2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Parcial2.Models.EntradaEmpacados", b =>
                {
                    b.Property<int>("EmpacadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PProducidosProductoDetalleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmpacadosId");

                    b.HasIndex("PProducidosProductoDetalleId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradaEmpacados");
                });

            modelBuilder.Entity("Parcial2.Models.PresentacionDetalles", b =>
                {
                    b.Property<int>("ProductoDetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntradaEmpacadosEmpacadosId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ExistenciaEmpacada")
                        .HasColumnType("REAL");

                    b.Property<float>("PesoTotal")
                        .HasColumnType("REAL");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoDetallesId");

                    b.HasIndex("EntradaEmpacadosEmpacadosId");

                    b.ToTable("PresentacionDetalles");
                });

            modelBuilder.Entity("Parcial2.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<float>("Existencia")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<double>("Ganancia")
                        .HasColumnType("REAL");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorInventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Parcial2.Models.ProductosDetalle", b =>
                {
                    b.Property<int>("ProductoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<float?>("ExistenciaEmpacada")
                        .HasColumnType("REAL");

                    b.Property<float?>("Precio")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoDetalleId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosDetalle");
                });

            modelBuilder.Entity("Parcial2.Models.ProductosUtilizados", b =>
                {
                    b.Property<int>("ProductosUtilizadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadUtilizados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntradaEmpacadosEmpacadosId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductoDetalleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductosUtilizadosId");

                    b.HasIndex("EntradaEmpacadosEmpacadosId");

                    b.ToTable("ProductosUtilizados");
                });

            modelBuilder.Entity("Parcial2.Models.EntradaEmpacados", b =>
                {
                    b.HasOne("Parcial2.Models.ProductosDetalle", "PProducidos")
                        .WithMany()
                        .HasForeignKey("PProducidosProductoDetalleId");

                    b.HasOne("Parcial2.Models.Productos", null)
                        .WithMany("EntradaEmpacados")
                        .HasForeignKey("ProductoId");

                    b.Navigation("PProducidos");
                });

            modelBuilder.Entity("Parcial2.Models.PresentacionDetalles", b =>
                {
                    b.HasOne("Parcial2.Models.EntradaEmpacados", null)
                        .WithMany("PresentacionDetalles")
                        .HasForeignKey("EntradaEmpacadosEmpacadosId");
                });

            modelBuilder.Entity("Parcial2.Models.ProductosDetalle", b =>
                {
                    b.HasOne("Parcial2.Models.Productos", "Producto")
                        .WithMany("ProductosDetalle")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Parcial2.Models.ProductosUtilizados", b =>
                {
                    b.HasOne("Parcial2.Models.EntradaEmpacados", null)
                        .WithMany("PUtilizados")
                        .HasForeignKey("EntradaEmpacadosEmpacadosId");
                });

            modelBuilder.Entity("Parcial2.Models.EntradaEmpacados", b =>
                {
                    b.Navigation("PUtilizados");

                    b.Navigation("PresentacionDetalles");
                });

            modelBuilder.Entity("Parcial2.Models.Productos", b =>
                {
                    b.Navigation("EntradaEmpacados");

                    b.Navigation("ProductosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
